### ISSUE TITLE
Cannot create package on pkgd

### ISSUE THREAD

**Issue by Metaxal** [racket/racket-pkg-website#73]
I'm trying to create a new package on pkgd.racket-lang.org but each time I click on 'save' it just reloads the page with all fields empty, and the package isn't created. It's using a git repo on github, with the path within repository.

**Comment by jeapostrophe** [comment]
Hmm, I just tried this and it worked immediately... do you get any message? Can you look at your browsers request log?

**Comment by Metaxal** [comment]
It eventually worked on the 5th attempt while trying to collect the request log, so I can't really provide meaningful feedback, sorry.

**Comment by Metaxal** [comment]
On the last attempt worked, I skipped tags and description, maybe that's the reason?

**Comment by Metaxal** [comment]
Hmm, I just create a new test package with both tags and description and it worked straight away. Weird.
I also tried updating the tags and description of my initial package and it didn't work on the first try, but worked on the second one.

**Comment by Metaxal** [comment]
See also #76
