### ISSUE TITLE
Package submission fails (with an empty form as result)

### ISSUE THREAD

**Issue by sschwarzer** [racket/racket-pkg-website#76]
I tried to enter a package at https://pkgd.racket-lang.org/pkgn/create with the information in the attached screenshots. The second attempt was without tags since there already had been a problem with the server not accepting a `.` in a tag, so I tried without tags to avoid other potential tag-related problems.

In both cases (see screenshots) the response from the package server was just an empty form (more precisely: only my mail address is pre-filled) and my package isn't in the index. There wasn't even the "Save failed" message on the response page.

The problem may be related to the new `git+https` "protocol", but I was able to enter another package with this protocol:
https://pkgd.racket-lang.org/pkgn/package/todo-txt . That said, I don't know if any of the software of the package server changed between entering the first (successful) and the second (unsuccessful) package.

![create_package5](https://user-images.githubusercontent.com/744533/120924329-7ba8ef00-c6d3-11eb-9552-4300f42ede47.png)

![create_package6](https://user-images.githubusercontent.com/744533/120924371-c7f42f00-c6d3-11eb-8207-06f03f57c5e0.png)

**Comment by sschwarzer** [comment]
I just tried again and was able to add the package data with a workaround:
- Adding with the data in screenshot 2 above failed again with only getting an empty form. If you want to check the logs, that was at about 2021-06-08 11:20 UTC.
- Then I retried and entered only essential data in the form, i. e. only package name, host and repository. I checked the "Avoid .git suffix ..." checkbox. Submitting this data succeeded.
- The remaining data (branch/commit, package description and tags) I added in separate edit steps to hopefully see if one of them would cause problems, but these edits all succeeded.

**Comment by jbclements** [comment]
Bump! Same problem, same solution.

**Comment by sschwarzer** [comment]
> Bump! Same problem, same solution.

Thanks for the heads-up.

I wouldn't call it a solution, though. ;-)

**Comment by jryans** [comment]
With https://github.com/racket/racket-pkg-website/pull/80 merged and deployed, this should now be fixed. 😄

The root cause ended up being a memory threshold that was set too low, causing the web server continuations to expire after only 2 minutes, which is why it worked sometimes: you had to submit the form within 2 minutes of loading it. This has been fixed, so you now have much more time to work through the form.
